apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- service.yml
images:
- name: app
  newName: ricardoandreh/aval-pratica-app
  newTag: 7762840d721fc6656c448a252af104cb66feebf2
